// Generated by CoffeeScript 1.8.0
(function() {
  (function(win) {
    var doc, docEl, refreshRem;
    doc = win.document;
    docEl = doc.documentElement;
    refreshRem = function() {
      var rem, width;
      width = docEl.getBoundingClientRect().width;
      if (width > 720) {
        width = 720;
      }
      rem = width / 20;
      rem = Math.max(24, rem);
      docEl.style.fontSize = rem + "px";
      return this;
    };
    win.addEventListener("resize", (function() {
      var tid;
      clearTimeout(tid);
      tid = setTimeout(refreshRem, 300);
    }), false);
    win.addEventListener("pageshow", (function(e) {
      var tid;
      if (e.persisted) {
        clearTimeout(tid);
        tid = setTimeout(refreshRem, 300);
      }
    }), false);
    return refreshRem();
  })(window);

}).call(this);
